services:
  postgres:
    image: postgres:15-alpine
    container_name: bom_comparison_db
    environment:
      POSTGRES_DB: bom_comparison
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Letmein_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 